spring:

  datasource:
    url: jdbc:mysql://18.189.54.77:3306/WECUP_DB?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: onAuspicious
    password: 1447
    driver-class-name: com.mysql.cj.jdbc.Driver
#  h2:
#    console:
#      enabled: true

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/cupTest
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

    data: classpath*:/data.sql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql:
        format_sql:

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  port: 5000

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400